// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  multiWordName = 12,
  unit = 13,
  Recipe = 1,
  Step = 2,
  StepDesc = 3,
  ResultName = 4,
  Ingredient = 5,
  Amount = 6,
  Unit = 7,
  IngredientType = 8
