// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {gridMultiWordName, multiWordName} from "./tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&SQVQTOOOOQO'#Cj'#CjO_QPO'#CiOOQS'#Cl'#ClQgQTOOQlQVOOO!WQTO'#CgO!]QTO,59TO!qQPO,59TOOQS-E6j-E6jOOQU'#C_'#C_OOQO'#C`'#C`OOQS'#Cc'#CcOOQS'#Cd'#CdOOQU'#Ce'#CeOOQU'#Ch'#ChOOQU'#Cf'#CfOOQU'#Cb'#CbO!vQTO'#CbO!{QTO'#CbOOQU'#C^'#C^O#TQPO'#C^OOQU'#Ck'#CkQlQVOOOOQU,59R,59RO#YQTO1G.oO!]QTO1G.oOOQU,58|,58|O!vQTO,58|OOQU'#Ca'#CaOOQU,58x,58xOOQU-E6i-E6iO!]QTO'#CmO#eQTO7+$ZO#eQTO7+$ZOOQU1G.h1G.hOOQS,59X,59XOOQS-E6k-E6kO#pQTO<<Gu",
  stateData: "#{~OgOS~OdPOhTO~OlUOoVO~OdPO~OcZOd^Oe]OiYOk[OlUOm_On_O~OdhO~Od^Oe]Ok[OlUOm_On_O~OojO~Od^O~Od^Oe]O~OjmO~OppOb]id]i~OppOb]qd]q~OppOb]yd]y~O",
  goto: "#qbPPcgkor!P!W!b!p!w!z#R#V#Z#a#gTfTgTdTgTeTgRneSdTgQiVQrjRtpZcTVgjpYbTVgjpRlcYaTVgjpSkbcRslZaTVgjpQWQZ`TVgjpTROSTQOSQgTRogQSORXSQqiSuqvRvr",
  nodeNames: "⚠ Recipe GridLine GridDivider GridStepDesc GridQuantity Ingredient Amount Unit IngredientType BackReference ResultName LastResult Step StepDesc",
  maxTerm: 32,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "'V~RfX^!gpq!gxy#[|}#p}!O#u!O!P$Q!Q![$`![!]$n!b!c$s!i!j$x!o!p%g!p!q&V#Q#R&c#T#U&h#y#z!g$f$g!g#BY#BZ!g$IS$I_!g$I|$JO!g$JT$JU!g$KV$KW!g&FU&FV!g~!lYg~X^!gpq!g#y#z!g$f$g!g#BY#BZ!g$IS$I_!g$I|$JO!g$JT$JU!g$KV$KW!g&FU&FV!g~#_P!Q![#b~#eQyz#k!Q![#b~#pOj~~#uOp~~#xP}!O#{~$QOi~~$TP!Q![$W~$]Pk~!Q![$W~$eRk~!O!P$Q!P!Q$Q!Q![$`~$sOo~~$xOl~~${P#f#g%O~%RP#]#^%U~%XP#W#X%[~%_P![!]%b~%gOh~~%jP#T#U%m~%pP#b#c%s~%vP#i#j%y~%|P#T#U&P~&SP#`#a%[~&YP!j!k&]~&`P!c!d%[~&hOm~~&kP#U#V&n~&qP#c#d&t~&wP#j#k&z~&}P#X#Y'Q~'VOn~",
  tokenizers: [0, gridMultiWordName, multiWordName],
  topRules: {"Recipe":[0,1]},
  tokenPrec: 0,
  termNames: {"0":"⚠","1":"@top","2":"GridLine","3":"GridDivider","4":"GridStepDesc","5":"GridQuantity","6":"Ingredient","7":"Amount","8":"Unit","9":"IngredientType","10":"BackReference","11":"ResultName","12":"LastResult","13":"Step","14":"StepDesc","15":"GridLine+","16":"Step+","17":"(\",\" Ingredient)+","18":"␄","19":"gridMultiWordName","20":"multiWordName","21":"unit","22":"%mainskip","23":"space","24":"gridMarker","25":"\"--\"","26":"gridQuantity","27":"amount","28":"\"@\"","29":"\"^\"","30":"\"above\"","31":"\":\"","32":"\",\""}
})
