// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  gridMultiWordName = 19,
  multiWordName = 20,
  unit = 21,
  Recipe = 1,
  GridLine = 2,
  GridDivider = 3,
  GridStepDesc = 4,
  GridQuantity = 5,
  Ingredient = 6,
  Amount = 7,
  Unit = 8,
  IngredientType = 9,
  BackReference = 10,
  ResultName = 11,
  LastResult = 12,
  Step = 13,
  StepDesc = 14
