// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  multiWordName = 14,
  unit = 15,
  Recipe = 1,
  Step = 2,
  StepDesc = 3,
  ResultName = 4,
  Ingredient = 5,
  Amount = 6,
  Unit = 7,
  IngredientType = 8,
  BackReference = 9,
  LastResult = 10
